TRUNCATE  
  pocket_users
  RESTART IDENTITY CASCADE;

TRUNCATE
  user_notecards
  RESTART IDENTITY CASCADE;

TRUNCATE
  user_notes
  RESTART IDENTITY CASCADE;

TRUNCATE
  user_deadlines
  RESTART IDENTITY CASCADE;